### ISSUE TITLE
Retrieving the fingerprint and access token

### ISSUE THREAD

**Issue by aeternias** [muhlba91/onyx-homeassistant-integration#13]
**Please describe your problem and question.**
I don't really understand how to get the access token or the fingerprint from the onyx.center.

**Linked Issues.**
If there are any linked issues, please link them here.

**Describe what you've tried so far.**
I tried reading the documentation but I don't understand what "sending it to the API endpoint" means.

I also don't understand what "You must use the returned API token to make at least one API request to make it permanent". How do I use it?

**Additional context.**
I'm using Home Assistant OS on a Raspberry Pi.

**Comment by muhlba91** [comment]
please follow https://github.com/hella-info/onyx_api#access-control to retrieve these values.

simply put you need to:
1/ go to Settings > Access Control in the ONYX app
2/ create a new temporary access code by clicking "+" and providing a name for the token
3/ use this token within 15 minutes to execute the API request as shown here: https://github.com/hella-info/onyx_api#example (use your generated code)
4/ this request returned the fingerprint and access token you need to use for this integration
