### ISSUE TITLE
Installation of integration fails, after ha core update to 2023.3.5

### ISSUE THREAD

**Issue by tbarth64** [muhlba91/onyx-homeassistant-integration#17]
Hi,

I updated my hassio from 2023.2.4 with onyx-homeassistant-integration V 3.0.0 to 2023.3.5. After that I updated the onyx integration with HACS to V 4.0.0, after resarting hassio i got these messages and the integration didn't work anymore:

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 12:17:22 (1 occurrences)
Last logged: 12:17:22

Setup failed for custom integration hella_onyx: Requirements for hella_onyx not found: ['onyx-client==5.0.1'].

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 12:16:49 (3 occurrences)
Last logged: 12:17:22

Unable to install package onyx-client==5.0.1: ERROR: Ignored the following versions that require a different python version: 5.0.1 Requires-Python >=3.11,<4.0 ERROR: Could not find a version that satisfies the requirement onyx-client==5.0.1 (from versions: 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1, 3.1.2, 4.0.0, 4.0.1) ERROR: No matching distribution found for onyx-client==5.0.1 [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.84-v8",
    "supervisor": "2023.03.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },

Best Regards,
Thomas

**Comment by muhlba91** [comment]
yes, i unfortunately upgraded to Python 3.11. i downgraded again and version 6.0.1+ is running on Python 3.10 now.

**Comment by tbarth64** [comment]
Great thanks, now it is working again.You can close the issue.Best regards ThomasAm 24.03.2023 um 17:36 schrieb Daniel Mühlbachler-Pietrzykowski ***@***.***>:﻿
yes, i unfortunately upgraded to Python 3.11. i downgraded again and version 6.0.1+ is running on Python 3.10 now.
