### ISSUE TITLE
Automated Exchange of Code to API Key and Fingerprint

### ISSUE THREAD

**Issue by muhlba91** [muhlba91/onyx-homeassistant-integration#6]
**Is your feature request related to a problem? Please describe.**
Currently, we have to create a code and exchange it for the API key and fingerprint using one manual HTTP request.
This is cumbersome and most users might struggle with such a setup flow/experience.

**Describe the solution you'd like.**
Implement retrieving the API key and fingerprint automatically by only supplying the code.
However, allow both ways to setup depending on the user's preference.

**Additional context.**
The `onyx-client` library already supports this exchange (https://github.com/muhlba91/onyx-client/blob/master/onyx_client/helpers/__init__.py#L10).
1) If the code is specified, use this flow.
2) If no code was specified, use the access token.
3) If none of above was specified, throw an error.

**Comment by clostermannshof** [comment]
👍 this is a great idea btw especially for beginners who want to use the integration and are not comfortable with calling an api
